5.17:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.17.out 5.17.cpp
	@echo "Done."
5.19:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.19.out 5.19.cpp
	@echo "Done."
5.20:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.20.out 5.20.cpp
	@echo "Done."
5.21:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.21.out 5.21.cpp
	@echo "Done."
5.23:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.23.out 5.23.cpp
	@echo "Done."
5.24:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.24.out 5.24.cpp
	@echo "Done."
5.25:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 5.25.out 5.25.cpp
	@echo "Done."
