6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.5:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.5.out 6.5.cpp
	@echo "Done."
6.7:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.7.out 6.7.cpp
	@echo "Done."
factMain:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.9/factMain.out 6.9/fact.cpp 6.9/factMain.cpp 
	@echo "Done."
6.10:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.10.out 6.10.cpp
	@echo "Done."
6.11:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.11.out 6.11.cpp
	@echo "Done."
tmp:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o tmp.out tmp.cpp
	@echo "Done."
6.12:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.12.out 6.12.cpp
	@echo "Done."
