6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.5:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.5.out 6.5.cpp
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
