6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.5:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.5.out 6.5.cpp
	@echo "Done."
6.7:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.7.out 6.7.cpp
	@echo "Done."
factMain:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.9/factMain.out 6.9/fact.cpp 6.9/factMain.cpp 
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
6.4:
	@g++ -pedantic -Wall -Wextra -std=c++11 -pedantic-errors -o 6.4.out 6.4.cpp
	@echo "Done."
